### ISSUE TITLE
Add flash option

### ISSUE THREAD

**Issue by ChristopheBoucaut** [geneanet/customCamera#54]

**Comment by ChristopheBoucaut** [comment]
- Permettre via JS de mettre le flash dans un état par défaut.
=> defaultFlash: 0 (disable) / 1 (active) / 2 (auto)

*Note : Si auto pas dispo, activer par défaut.*
- Permettre d'afficher ou non un bouton de switch sur l'état du flash
=> switchFlash: true (active switch) / false (disable switch)

**Comment by Tboy70** [comment]
Lors d'un refus de photo, on revient avec le mode de flash avec lequel la photo a été prise ou celui par défaut ?

**Comment by ChristopheBoucaut** [comment]
celui au moment de la prise de photo.

**Comment by Tboy70** [comment]
fix by #63
